### ISSUE TITLE
ServerStartMojo Mongo is not starting

### ISSUE THREAD

**Issue by dcrissman** [dcrissman/lightblue-build-testing-plugin#1]
I believe this is because the test harness framework was designed to be used within a test suite, whereas this is more of a standalone server instance. Because the test harness is not being run from within a junit context, the BeforeClass, AfterClass, ClassRule, etc annotations are not working. 

Either find a way to make the annotations work (maybe something similar to https://github.com/lightblue-platform/lightblue-client/blob/master/lightblue-client-integration-test/src/main/java/com/redhat/lightblue/client/integration/test/BeforeAfterTestRule.java) OR perhaps a new (simpler?) implementation of the in-memory server is needed.

`
INFO: Exception in monitor thread while connecting to server localhost:8000
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	... 3 more
`

**Comment by dcrissman** [comment]
Thinking some more, we don't really want the After and AfterClass annotations to fire until ServerStopMojo is executed.
